proxy:
  port: 8080
  landing-page: /app/namco
  authentication: none
  admin-groups: admins
  container-log-path: ./container-logs
  container-backend: docker
  container-wait-time: 10000
  heartbeat-rate: 1000 # the user's browser will send a heartbeat call every heartbeat-rate milliseconds (10s as default)
  heartbeat-timeout: 6000 # if the server does not receive a heartbeat for heartbeat-timeout milliseconds, the relevant proxy will be released (60s as default)
  hide-navbar: true
  users:
  - name: jack
    password: password
    groups: admins
  docker:
    internal-networking: true
  specs:
  - id: namco
    display-name: Namco
    description: Webapp for analysis of microbiome data
    container-cmd: ["R", "-e", "shiny::runApp('/srv/shiny-server/', host = '0.0.0.0', port = 3838)"]
    #container-cmd: ["/usr/bin/shiny-server.sh"]
    container-network: namco_sp-net
    container-image: gitlab.lrz.de:5005/biomedbigdata/namco:latest
    #container-cpu-limit: 2

logging:
  file:
    name: ./shinyproxy.log

server:
  useForwardHeaders: true

